@BookingApi.WebApi_HostAddress = https://localhost:7071

# Get available homes
GET {{BookingApi.WebApi_HostAddress}}/api/available-homes
Accept: application/json

###

# Access Swagger UI
GET {{BookingApi.WebApi_HostAddress}}/swagger
Accept: text/html

###
